export const materialsWithToys = {
  "Plastic": [
    { name: "Action Figure", quantity: 150 },
    { name: "Basketball Hoop", quantity: 100 },
    { name: "Bubble Maker", quantity: 100 },
    { name: "Building Blocks", quantity: 200 },
    { name: "Electric Guitar", quantity: 100 },
    { name: "Flying Drone", quantity: 200 },
    { name: "LEGO Spaceship", quantity: 250 },
    { name: "Magic Set", quantity: 100 },
    { name: "Play-Doh Set", quantity: 50 },
    { name: "Race Car Track", quantity: 300 },
    { name: "Remote Control Car", quantity: 150 },
    { name: "Robot Kit", quantity: 200 },
    { name: "Toy Airplane", quantity: 100 },
    { name: "Toy Cash Register", quantity: 150 },
    { name: "Toy Drum Set", quantity: 200 },
    { name: "Toy Kitchen Set", quantity: 300 },
    { name: "Toy Soldier Set", quantity: 150 },
    { name: "Toy Tool Set", quantity: 200 },
    { name: "Water Gun", quantity: 150 },
  ],
  "Paint": [
    { name: "Action Figure", quantity: 20 },
    { name: "Building Blocks", quantity: 30 },
    { name: "Doll House", quantity: 100 },
    { name: "Bicycle", quantity: 50 },
    { name: "Puzzle", quantity: 30 },
    { name: "Pirate Ship", quantity: 50 },
    { name: "Robot Kit", quantity: 30 },
    { name: "Toy Airplane", quantity: 30 },
    { name: "Toy Soldier Set", quantity: 20 },
    { name: "Toy Train Set", quantity: 50 },
    { name: "Superhero Costume", quantity: 30 },
  ],
  "Steel Rods": [
    { name: "Basketball Hoop", quantity: 200 },
    { name: "Bicycle", quantity: 400 },
  ],
  "Rubber": [
    { name: "Bicycle", quantity: 100 },
    { name: "Bubble Maker", quantity: 20 },
    { name: "Remote Control Car", quantity: 50 },
    { name: "Toy Drum Set", quantity: 50 },
    { name: "Toy Cash Register", quantity: 30 },
    { name: "Water Gun", quantity: 20 },
  ],
  "Wood": [
    { name: "Doll House", quantity: 500 },
    { name: "Electric Guitar", quantity: 300 },
    { name: "Pirate Ship", quantity: 400 },
    { name: "Rocking Horse", quantity: 500 },
    { name: "Toy Kitchen Set", quantity: 200 },
    { name: "Toy Train Set", quantity: 400 },
  ],
  "Glue": [{ name: "Doll House", quantity: 50 }],
  "Copper Wire": [
    { name: "Electric Guitar", quantity: 50 },
    { name: "Robot Kit", quantity: 20 },
  ],
  "Metal Screws": [
    { name: "Flying Drone", quantity: 50 },
    { name: "Race Car Track", quantity: 20 },
    { name: "Remote Control Car", quantity: 10 },
    { name: "Robot Kit", quantity: 30 },
    { name: "Toy Airplane", quantity: 20 },
    { name: "Toy Drum Set", quantity: 40 },
    { name: "Toy Kitchen Set", quantity: 30 },
    { name: "Toy Tool Set", quantity: 20 },
    { name: "Toy Train Set", quantity: 30 },
  ],
  "Magnets": [{ name: "LEGO Spaceship", quantity: 20 }],
  "Cardboard": [
    { name: "Board Game", quantity: 300 },
    { name: "Magic Set", quantity: 50 },
    { name: "Puzzle", quantity: 200 },
  ],
  "Clay": [{ name: "Play-Doh Set", quantity: 300 }],
  "Fabric": [
    { name: "Magic Set", quantity: 30 },
    { name: "Pirate Ship", quantity: 50 },
    { name: "Stuffed Dinosaur", quantity: 150 },
    { name: "Stuffed Unicorn", quantity: 150 },
    { name: "Superhero Costume", quantity: 200 },
    { name: "Teddy Bear", quantity: 150 },
  ],
  "Cotton": [
    { name: "Stuffed Dinosaur", quantity: 100 },
    { name: "Stuffed Unicorn", quantity: 100 },
    { name: "Teddy Bear", quantity: 100 },
  ],
  "Thread": [
    { name: "Stuffed Dinosaur", quantity: 20 },
    { name: "Stuffed Unicorn", quantity: 20 },
    { name: "Teddy Bear", quantity: 20 },
  ],
  "Velcro": [{ name: "Superhero Costume", quantity: 50 }],
  "Springs": [
    { name: "Flying Drone", quantity: 30 },
    { name: "Remote Control Car", quantity: 10 },
    { name: "Water Gun", quantity: 10 },
  ],
  "Rubber Bands": [{ name: "Water Gun", quantity: 20 }],

  // Randomly assigned materials to toys
  "Aluminum Sheets": [{ name: "Toy Train Set", quantity: 200 }],
  "Bamboo": [{ name: "Rocking Horse", quantity: 300 }],
  "Brass Fittings": [{ name: "Toy Kitchen Set", quantity: 100 }],
  "Buttons": [{ name: "Teddy Bear", quantity: 50 }],
  "Ceramic": [{ name: "Magic Set", quantity: 20 }],
  "Epoxy Resin": [{ name: "Robot Kit", quantity: 100 }],
  "Feathers": [{ name: "Superhero Costume", quantity: 50 }],
  "Foam": [{ name: "Stuffed Dinosaur", quantity: 80 }],
  "Fur": [{ name: "Stuffed Unicorn", quantity: 70 }],
  "Glass": [{ name: "Pirate Ship", quantity: 100 }],
  "Glass Beads": [{ name: "LEGO Spaceship", quantity: 50 }],
  "Leather": [{ name: "Bicycle", quantity: 200 }],
  "Nails": [{ name: "Doll House", quantity: 30 }],
  "Plastic Pellets": [{ name: "Race Car Track", quantity: 400 }],
  "Polyester": [{ name: "Stuffed Dinosaur", quantity: 50 }],
  "Polystyrene": [{ name: "Flying Drone", quantity: 100 }],
  "Ribbons": [{ name: "Teddy Bear", quantity: 30 }],
  "Sandpaper": [{ name: "Toy Tool Set", quantity: 10 }],
  "Silicone": [{ name: "Water Gun", quantity: 30 }],
  "Silk": [{ name: "Superhero Costume", quantity: 100 }],
  "Velvet": [{ name: "Teddy Bear", quantity: 60 }],
  "Wool": [{ name: "Stuffed Unicorn", quantity: 90 }],
  "Yarn": [{ name: "Stuffed Dinosaur", quantity: 60 }],
};
